2024-10-27 10:54:53,455 - WARNING - Werkzeug appears to be used in a production deployment. Consider switching to a production web server instead.
2024-10-27 10:54:53,467 - WARNING -  * Debugger is active!
2024-10-27 10:54:53,474 - INFO -  * Debugger PIN: 883-533-741
2024-10-27 10:54:59,058 - INFO - 127.0.0.1 - - [27/Oct/2024 10:54:59] "GET /all-images HTTP/1.1" 200 -
2024-10-27 10:55:05,220 - INFO - 127.0.0.1 - - [27/Oct/2024 10:55:05] "GET /all-images HTTP/1.1" 200 -
2024-10-27 10:55:05,223 - INFO - Client connected
2024-10-27 10:55:05,229 - INFO - 127.0.0.1 - - [27/Oct/2024 10:55:05] "GET /all-images HTTP/1.1" 200 -
2024-10-27 10:55:05,244 - INFO - 127.0.0.1 - - [27/Oct/2024 10:55:05] "[36mGET /images/nvcamtest_7563_s00_00168%202.jpg HTTP/1.1[0m" 304 -
2024-10-27 10:57:54,765 - INFO - Client disconnected. Reason: unknown
2024-10-27 10:57:54,767 - INFO - 127.0.0.1 - - [27/Oct/2024 10:57:54] "[35m[1mGET /socket.io/?EIO=4&transport=websocket HTTP/1.1[0m" 500 -
2024-10-27 10:57:54,770 - ERROR - Error on request:
Traceback (most recent call last):
  File "/Users/aahil/Edhitha/edhithaGCS/.venv/lib/python3.12/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/Users/aahil/Edhitha/edhithaGCS/.venv/lib/python3.12/site-packages/werkzeug/serving.py", line 336, in execute
    write(b"")
  File "/Users/aahil/Edhitha/edhithaGCS/.venv/lib/python3.12/site-packages/werkzeug/serving.py", line 261, in write
    assert status_set is not None, "write() before start_response"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: write() before start_response
2024-10-27 10:57:54,919 - INFO - Client connected
2024-10-27 10:57:54,920 - INFO - 127.0.0.1 - - [27/Oct/2024 10:57:54] "GET /all-images HTTP/1.1" 200 -
2024-10-27 10:57:54,924 - INFO - 127.0.0.1 - - [27/Oct/2024 10:57:54] "GET /all-images HTTP/1.1" 200 -
2024-10-27 10:57:54,930 - INFO - 127.0.0.1 - - [27/Oct/2024 10:57:54] "[36mGET /images/nvcamtest_7563_s00_00168%202.jpg HTTP/1.1[0m" 304 -
2024-10-27 11:02:06,834 - INFO - Client disconnected. Reason: unknown
2024-10-27 11:02:06,836 - INFO - 127.0.0.1 - - [27/Oct/2024 11:02:06] "[35m[1mGET /socket.io/?EIO=4&transport=websocket HTTP/1.1[0m" 500 -
2024-10-27 11:02:06,838 - ERROR - Error on request:
Traceback (most recent call last):
  File "/Users/aahil/Edhitha/edhithaGCS/.venv/lib/python3.12/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/Users/aahil/Edhitha/edhithaGCS/.venv/lib/python3.12/site-packages/werkzeug/serving.py", line 336, in execute
    write(b"")
  File "/Users/aahil/Edhitha/edhithaGCS/.venv/lib/python3.12/site-packages/werkzeug/serving.py", line 261, in write
    assert status_set is not None, "write() before start_response"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: write() before start_response
2024-10-27 11:02:06,990 - INFO - Client connected
2024-10-27 11:02:06,992 - INFO - 127.0.0.1 - - [27/Oct/2024 11:02:06] "GET /all-images HTTP/1.1" 200 -
2024-10-27 11:02:06,995 - INFO - 127.0.0.1 - - [27/Oct/2024 11:02:06] "GET /all-images HTTP/1.1" 200 -
2024-10-27 11:02:07,002 - INFO - 127.0.0.1 - - [27/Oct/2024 11:02:07] "[36mGET /images/nvcamtest_7563_s00_00168%202.jpg HTTP/1.1[0m" 304 -
2024-10-27 11:04:00,310 - INFO - Client disconnected. Reason: unknown
2024-10-27 11:04:00,450 - INFO - 127.0.0.1 - - [27/Oct/2024 11:04:00] "GET /all-images HTTP/1.1" 200 -
2024-10-27 11:04:00,451 - INFO - Client connected
2024-10-27 11:04:00,453 - INFO - 127.0.0.1 - - [27/Oct/2024 11:04:00] "GET /all-images HTTP/1.1" 200 -
2024-10-27 11:04:00,461 - INFO - 127.0.0.1 - - [27/Oct/2024 11:04:00] "[36mGET /images/nvcamtest_7563_s00_00168%202.jpg HTTP/1.1[0m" 304 -
